### ISSUE TITLE
Feature Request: Week Overview

### ISSUE THREAD

**Issue by Non-J** [itzmeowww/menu-memo#5]
There should be a way to get the week overview so that it is possible to plan which meal I should skip without opening the full spreadsheet.

I'll try to add it but the project is hard to test locally.

**Comment by itzmeowww** [comment]
use `npm start` to start the server
and go to localhost/**cmd** to test

**Comment by Non-J** [comment]
Noooooo. I mean like local database mocking so that I don't have to deal with generating google sheet key อะ
